### ISSUE TITLE
Interface order

### ISSUE THREAD

**Issue by sthorsen** [rtib/tib-debnet#15]
Hi I'm having some issues ordering my interfaces and bonding

I create a bond interface bond0 and then I create 2 interfaces with tagged vlans bond0.50 and bond0.403. But on matter what I do, I always get the bond0 definition in the bottom of '/etc/network/interfaces'. Which result that the network wont come up because bond0.50 is the first interface and it does not know bond0 yet.

Do you have any knowledge about if this is an issue?

**Comment by rtib** [comment]
Did you checked out the $order attribute? Resources of type debnet::iface::bond have a preset of 60, additional to the order you give to the particular resource instances. Keep the default for your bond0 and add some positive value to tagged bond0 child interfaces.

Interface stanza are generated by growing order.

**Comment by sthorsen** [comment]
Hi and thank you for your replay :)

I have tried to set the bond0 interface order attribute higher then the child interfaces. But it makes no difference.

Here is my code:
manifest.pp
```
sn::base::network { '$fqdn-bond0': # interface 1
                ifname => 'bond0',
                nics => ['eno3', 'eno4'],
                order => 0,
        }

        # attached to VLAN 50
        sn::base::network { '$fqdn-bond0.50' : # interface 2
                ip => 'xxx.xxx.xxx.xxx',
                netmask => 'xxx.xxx.xxx.xxx',
                nics => 'bond0.50',
                order => 1,
        }

        # attached to VLAN 403
        sn::base::network { '$fqdn-bond0.403' : # interface 2
                ip => 'xxx.xxx.xxx.xxx',
                netmask => 'xxx.xxx.xxx.xxx',
                gateway => 'xxx.xxx.xxx.xxx',
                nics => 'bond0.403',
                order => 2,
        }

```
network.pp
```
define sn::base::network (
        $ifname = undef,
        $ip = undef,
        $netmask = undef,
        $gateway = undef,
        $nics = undef,
        $order = undef,
) {
        if (is_array($nics)) {
                debnet::iface::bond { 'bonding':
                        ifname => $ifname,
                        ports => $nics,
                        mode => 'active-backup',
                        method => 'manual',
                        order => $order,
                }
        } else {
                debnet::iface { $nics:
                        method => 'static',
                        address => $ip,
                        netmask => $netmask,
                        gateway => $gateway,
                        routes => {
                        },
                        dns_nameservers => ['xxx.xxx.xxx.xxx'],
                        order => $order,
                }
        }
}
```

**Comment by rtib** [comment]
Ok. You're using bond and static configs mixed. The point is, that debnet::iface::bond will create iface stanzas for all ports using 50 + $order and one iface for the bonding interface itself with 60 + $order. Order of the latter will increase further by 50 due to the method 'manual', so your bond0 will end up at order 110. Stanzas implementing static configurations will add 40 to their order. Thus, you need to add at least 71 to your static iface declarations to get them below of the bond stanza.

**Comment by sthorsen** [comment]
Thank you, that did the trick :)
