### ISSUE TITLE
Please add Debian Jessie support

### ISSUE THREAD

**Issue by pdirksen** [rtib/tib-debnet#3]
This module should work in generell in all debian releases.
Please update the module description and configuration.

Update: Debian Jessie additionally has `source /etc/network/interfaces.d/*` as its first line (besides comments).

**Comment by pdirksen** [comment]
In case you don't have jessie installed, here is a typical example:

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet dhcp
```

**Comment by rtib** [comment]
I'm looking forward to test the module against Debian Jessie, however, the source feature of interfaces (5) i found rather obstructive when implementing the module to generate a conflict-free configuration.

**Comment by rtib** [comment]
Actually, I won't add support for the source keyword, however, the module is supporting the configuration of more recent distributions including Debian jessie. The next release will fix this issue, so i'm going to close it.
